name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt install --yes podman
      - name: Run test
        run: make test
